### ISSUE TITLE
用thinkPHP8项目运行一下，报了一堆错。。suyar/php:8.2-fpm

### ISSUE THREAD

**Issue by Joe3160** [suyar/docker-php#3]
**在php容器下执行：php think**
```shell
php think

PHP Warning:  PHP Startup: Unable to load dynamic library 'Core' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/Core (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/Core: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/Core.so (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/Core.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'Core' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/Core (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/Core: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/Core.so (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/Core.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'ctype' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/ctype (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/ctype: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/ctype.so (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/ctype.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'ctype' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/ctype (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/ctype: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/ctype.so (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/ctype.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'curl' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/curl (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/curl: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/curl.so (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/curl.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

。。。。。。。。。

root@5e1cac71f157:/var/www/html# ls /usr/local/lib/php/extensions/no-debug-non-zts-20220829
amqp.so    bz2.so       enchant.so  gd.so       igbinary.so  lzf.so        msgpack.so  pcntl.so      pgsql.so    sodium.so  timezonedb.so  xsl.so   zip.so
apcu.so    calendar.so  event.so    gettext.so  imagick.so   memcached.so  mysqli.so   pdo_mysql.so  redis.so    swoole.so  uuid.so        yac.so
bcmath.so  decimal.so   exif.so     gmp.so      intl.so      mongodb.so    opcache.so  pdo_pgsql.so  sockets.so  tidy.so    xlswriter.so   yaml.so
root@5e1cac71f157:/var/www/html# ls /usr/local/lib/php/extensions/no-debug-non-zts-20220829|grep ctype.so
root@5e1cac71f157:/var/www/html#
```

docker-composer文件

``` yaml
  PHP:
    image: suyar/php:8.2-fpm
    #image: php:8.2-cli
    container_name: app-php
    ports:
     - 9082:9000
    volumes:
      - ./www:/var/www/html:rw
      - /etc/localtime:/etc/localtime
```

**Comment by suyar** [comment]
麻烦提供一下镜像版本

**Comment by Joe3160** [comment]
> 麻烦提供一下镜像版本

suyar/php:8.2-fpm 
suyar/php:8.3-fpm 
都不行。。

完整 docker-composer
```yaml
services:
  NGINX:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - 8000:80
    volumes:
      - ./www:/var/www/html
      - ./nginx/conf:/etc/nginx/conf.d:ro # nginx 配置
      - ./nginx/logs:/var/log/nginx # nginx 日志
      - /etc/localtime:/etc/localtime
    networks:
      - net-app
  PHP:
    image: suyar/php:8.2-fpm
    #image: php:8.2-cli
    container_name: app-php
    ports:
     - 9082:9000
    volumes:
      - ./www:/var/www/html:rw
      #- ./php:/usr/local/etc/php # PHP配置信息
      - /etc/localtime:/etc/localtime
    depends_on:
     - REDIS
     - MYSQL
    networks:
     - net-app
  MYSQL:
    image: mysql:latest
    container_name: app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: blog
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      #- ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    ports:
     - 3308:3306     
    networks:
      - net-app
  REDIS:
    image: redis:latest
    container_name: app-redis
    ports:
     - 6378:6379 
    networks:
      - net-app
    volumes:
      - ./redis/data:/data
networks:
  net-app:
    driver: bridge
```

**Comment by suyar** [comment]
我这边正常哦：

```
root@Yoga:/www/suyar# docker run -itd -v /www/suyar/tp:/data --name php82 suyar/php:8.2-fpm
a86494d050093eeb283c7654dd13bb7af1e66f8fa9eeb24c9a095236cba7479d
root@Yoga:/www/suyar# docker exec -it php82 bash
root@a86494d05009:/var/www/html# cd /data/
root@a86494d05009:/data# ls -la
total 108
drwxr-xr-x 10 root root  4096 Feb  9 20:32 .
drwxr-xr-x  1 root root  4096 Feb  9 20:33 ..
-rw-r--r--  1 root root   162 Feb  9 20:32 .example.env
-rw-r--r--  1 root root   115 Feb  9 20:32 .gitignore
-rw-r--r--  1 root root  2038 Feb  9 20:32 .travis.yml
-rw-r--r--  1 root root  1822 Feb  9 20:32 LICENSE.txt
-rw-r--r--  1 root root  2037 Feb  9 20:32 README.md
drwxr-xr-x  3 root root  4096 Feb  9 20:32 app
-rw-r--r--  1 root root  1144 Feb  9 20:32 composer.json
-rw-r--r--  1 root root 37221 Feb  9 20:32 composer.lock
drwxr-xr-x  2 root root  4096 Feb  9 20:32 config
drwxr-xr-x  2 root root  4096 Feb  9 20:32 extend
drwxr-xr-x  3 root root  4096 Feb  9 20:32 public
drwxr-xr-x  2 root root  4096 Feb  9 20:32 route
drwxr-xr-x  2 root root  4096 Feb  9 20:32 runtime
-rw-r--r--  1 root root   180 Feb  9 20:32 think
drwxr-xr-x  8 root root  4096 Feb  9 20:32 vendor
drwxr-xr-x  2 root root  4096 Feb  9 20:32 view
root@a86494d05009:/data# php think
version 8.1.2

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -V, --version         Display this console version
  -q, --quiet           Do not output any message
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  clear             Clear runtime file
  help              Displays help for a command
  list              Lists commands
  run               PHP Built-in Server for ThinkPHP
  version           show thinkphp framework version
 make
  make:command      Create a new command class
  make:controller   Create a new resource controller class
  make:event        Create a new event class
  make:listener     Create a new listener class
  make:middleware   Create a new middleware class
  make:model        Create a new model class
  make:service      Create a new Service class
  make:subscribe    Create a new subscribe class
  make:validate     Create a validate class
 optimize
  optimize:route    Build app route cache.
  optimize:schema   Build database schema cache.
 route
  route:list        show route list.
 service
  service:discover  Discover Services for ThinkPHP
 vendor
  vendor:publish    Publish any publishable assets from vendor packages
```

```
root@a86494d05009:/data# php -v
PHP 8.2.27 (cli) (built: Feb  4 2025 04:26:00) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.27, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.27, Copyright (c), by Zend Technologies
root@a86494d05009:/data# php -m
[PHP Modules]
amqp
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
decimal
dom
enchant
event
exif
fileinfo
filter
gd
gettext
gmp
hash
iconv
igbinary
imagick
intl
json
libxml
lzf
mbstring
memcached
mongodb
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
random
readline
redis
Reflection
session
SimpleXML
sockets
sodium
SPL
sqlite3
standard
swoole
tidy
timezonedb
tokenizer
uuid
xlswriter
xml
xmlreader
xmlwriter
xsl
yac
yaml
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

按照下列步骤检查下输出贴出来：
1. 检查是不是最新的镜像 `docker images --digests|grep suyar/php`
2. 查看容器php-fpm进程是否正常 `docker top app-php`
3. 进入容器查看php版本和模块 `php-v` `php -m`

**Comment by Joe3160** [comment]
```yml
PHP:
    image: suyar/php:8.2-fpm
    #image: php:8.2-cli
    container_name: app-php
    ports:
     - 9082:9000
    volumes:
      - ./www:/var/www/html:rw
      #- ./php:/usr/local/etc/php # 这里明明注释了，里面的php.ini居然生效了，可能是旧容器的影响
      - /etc/localtime:/etc/localtime
```
找到问题了，是我启用了php 服务中的 ` ./php:/usr/local/etc/php` 挂载，造成容器配置文件的丢失。。。。
